SELECT USER
FROM DUAL;

-- DB설계 취합

-- 1. 계정테이블
CREATE TABLE ACCOUNT
( AC_NO     NUMBER
, CONSTRAINT AC_NO_PK PRIMARY KEY(AC_NO)
);

-- 2. 관리자 테이블
CREATE TABLE ADMIN
( AD_ID     VARCHAR2(30)    
, AD_PW     VARCHAR2(30)    NOT NULL
, CONSTRAINT AD_ID_PK PRIMARY KEY(AD_ID)
);

-- 1순위
-- 3. 질문 분류 테이블
CREATE TABLE FAQ_SORT
( QS_NO     NUMBER
, NAME      VARCHAR2(20)   
, CONSTRAINT QS_NO_PK   PRIMARY KEY(QS_NO)
);

-- 4. 공지사항 분류 테이블
CREATE TABLE NOTICE_SORT
( NOS_NO    NUMBER
, NAME      VARCHAR2(20)
, CONSTRAINT NOS_NO_PK  PRIMARY KEY(NOS_NO)
);

-- 5. 신고사유 테이블
CREATE TABLE REPORT_WHY
( WHY_NO    NUMBER
, TITLE     VARCHAR2(200)
, CONSTRAINT WHY_NO_PK PRIMARY KEY(WHY_NO)
);

-- 6. 신고 처리상태 테이블
CREATE TABLE REPORT_STATUS
( STATUS_NO     NUMBER
, STATUSNAME    VARCHAR2(20)
, AD_ID         VARCHAR2(30)
, CONSTRAINT STATUS_NO_PK PRIMARY KEY(STATUS_NO)
, CONSTRAINT AD_ID_FK FOREIGN KEY(AD_ID)
            REFERENCES ADMIN(AD_ID)
);

-- 7. 서울시 구 (1순위)
CREATE TABLE GU
( GU_NO NUMBER
, GUNAME VARCHAR2(30) NOT NULL
,CONSTRAINT GU_GU_NO_PK PRIMARY KEY (GU_NO)
);

-- 8. 점수 (1순위)
CREATE TABLE SCORE
( SCORENO NUMBER
, SCORENAME NUMBER(1)
,CONSTRAINT SCORE_SCORENO_PK PRIMARY KEY(SCORENO)
);

-- 9. 개인정보
CREATE TABLE PERSONAL
( PE_ID         VARCHAR2(30)    NOT NULL
, AC_NO         NUMBER          NOT NULL
, NAME          VARCHAR2(30)    NOT NULL
, TEL           VARCHAR2(30)    NOT NULL
, NICKNAME      VARCHAR2(30)    NOT NULL
, PW            VARCHAR2(30)    NOT NULL
, EMAIL         VARCHAR2(30)    NOT NULL
, ROADADDR      VARCHAR2(50)    NOT NULL
, DETAILADDR    VARCHAR2(100)   NOT NULL
, PROFILE       VARCHAR2(500)
, PEDATE        DATE            NOT NULL
, CONSTRAINT PERSONAL_PE_ID_PK PRIMARY KEY(PE_ID)
, CONSTRAINT PERSONAL_AC_NO_FK FOREIGN KEY(AC_NO)
             REFERENCES ACCOUNT(AC_NO)
, CONSTRAINT PERSONAL_TEL_UK UNIQUE(TEL)
, CONSTRAINT PERSONAL_NICKNAME_UK UNIQUE(NICKNAME)
);

-- 10. 거주여부
CREATE TABLE RESIDENCE      -- 거주여부 (1순위)
( RES_NO        NUMBER          NOT NULL
, RESIDENCENAME VARCHAR2(10)    NOT NULL
);

ALTER TABLE RESIDENCE ADD CONSTRAINT RES_NO_PK PRIMARY KEY(RES_NO);

-- 11. 탈퇴사유
CREATE TABLE WITHDRAWAL_WHY
( WIR_NO NUMBER
, WHY VARCHAR2(50)
, CONSTRAINT WITHDRAWAL_WHY_NO PRIMARY KEY(WIR_NO)
);


--2순위
-- 12.서울시 동 (2순위)
CREATE TABLE DONG
( DONG_NO NUMBER
, GU_NO NUMBER
, DONGNAME VARCHAR2(30) NOT NULL
,CONSTRAINT DONG_DONG_NO_PK PRIMARY KEY(DONG_NO)
,CONSTRAINT DONG_GU_NO_FK FOREIGN KEY(GU_NO)
REFERENCES GU (GU_NO)
);

-- 13. 탈퇴회원 테이블
CREATE TABLE WITHDRAWAL
( WI_NO     NUMBER
, AC_NO     NUMBER
, WIR_NO    NUMBER
, COMMENTS   VARCHAR2(300)
, WIDATE    DATE
, ID        VARCHAR2(30)
, NAME      VARCHAR2(30)
, TEL       VARCHAR2(30)
, CONSTRAINT WI_NO_PK PRIMARY KEY(WI_NO)
, CONSTRAINT AC_NO_FK   FOREIGN KEY(AC_NO)
            REFERENCES ACCOUNT(AC_NO)
, CONSTRAINT WIR_NO_FK  FOREIGN KEY(WIR_NO)
            REFERENCES WITHDRAWAL_WHY(WIR_NO)
);
--==> Table WITHDRAWAL이(가) 생성되었습니다.
DROP TABLE WITHDRAWAL;

-- 14. 공지사항
CREATE TABLE NOTICE
( NO_NO     NUMBER          NOT NULL
, AD_ID     VARCHAR2(30)    NOT NULL
, NOS_NO    NUMBER          NOT NULL
, TITLE     VARCHAR2(100)
, CONTENT   VARCHAR2(500)
, NODATE    DATE
, CONSTRAINT NOTICE_NO_NO_PK PRIMARY KEY(NO_NO)
, CONSTRAINT NOTICE_AD_ID_FK FOREIGN KEY(AD_ID)
             REFERENCES ADMIN(AD_ID)
, CONSTRAINT NOTICE_NOS_NO_FK FOREIGN KEY(NOS_NO)
             REFERENCES NOTICE_SORT(NOS_NO)
);

-- 15. 자주 묻는 질문
CREATE TABLE FAQ
( FAQ_NO    NUMBER          NOT NULL
, AD_ID     VARCHAR2(30)    NOT NULL
, QS_NO     NUMBER          NOT NULL
, TITLE     VARCHAR2(100)
, CONTENT   VARCHAR2(500)
, CONSTRAINT FAQ_NO_PK PRIMARY KEY(FAQ_NO)
, CONSTRAINT FAQ_AD_ID_FK FOREIGN KEY(AD_ID)
             REFERENCES ADMIN(AD_ID)
, CONSTRAINT FAQ_QS_NO_FK FOREIGN KEY(QS_NO)
             REFERENCES FAQ_SORT(QS_NO)
);

-- 16. 서비스 소개 게시판
CREATE TABLE INTRODUCTION
( IN_NO     NUMBER          NOT NULL
, AD_ID     VARCHAR2(30)    NOT NULL
, CONTENT   VARCHAR2(500)
, CONSTRAINT INTRO_IN_NO_PK PRIMARY KEY(IN_NO)
, CONSTRAINT INTRO_AD_ID_FK FOREIGN KEY(AD_ID)
             REFERENCES ADMIN(AD_ID)
);

-- 17. 체크리스트
CREATE TABLE CHECKLIST      -- 체크리스트 (2순위)
( CHECK_NO  NUMBER          NOT NULL
, AC_NO     NUMBER          NOT NULL
, RES_NO    NUMBER          NOT NULL
, CHECKDATE DATE
, TITLE     VARCHAR2(50)    NOT NULL
, ROADADDR  VARCHAR2(100)   NOT NULL
, DONG_NO   NUMBER          NOT NULL
, WIDO      VARCHAR2(30)
, GYEONGDO  VARCHAR2(30)
, CONSTRAINT CHECKLIST_NO_PK PRIMARY KEY(CHECK_NO)
, CONSTRAINT CHECKLIST_ACNO_FK FOREIGN KEY(AC_NO)
            REFERENCES ACCOUNT(AC_NO)
, CONSTRAINT CHECKLIST_RESNO_FK FOREIGN KEY(RES_NO)
            REFERENCES RESIDENCE(RES_NO)
, CONSTRAINT CHECKLIST_DONGNO_FK FOREIGN KEY(DONG_NO)
            REFERENCES DONG(DONG_NO)
);


--3순위
-- 18. 신고(체크리스트) 테이블
CREATE TABLE REPORT_CHECK
( RPCHECK_NO    NUMBER
, REPORTDATE    DATE
, CHECK_NO      NUMBER
, AC_NO         NUMBER        
, WHY_NO        NUMBER     
, WHY           VARCHAR2(500)
, STATUS_NO     NUMBER
, CONSTRAINT RPCHECK_NO_PK  PRIMARY KEY(RPCHECK_NO)
, CONSTRAINT RPCHECK_NO_FK    FOREIGN KEY(CHECK_NO)
                REFERENCES CHECKLIST(CHECK_NO)
, CONSTRAINT RPCHECK_AC_NO_FK   FOREIGN KEY(AC_NO)
                REFERENCES ACCOUNT(AC_NO)
, CONSTRAINT RPCHECK_WHY_NO_FK  FOREIGN KEY(WHY_NO)
                REFERENCES REPORT_WHY(WHY_NO)
, CONSTRAINT RPCHECK_STATUS_NO_FK   FOREIGN KEY(STATUS_NO)
                REFERENCES REPORT_STATUS(STATUS_NO)
);

-- 19. 코멘트
CREATE TABLE CONTENT
( CHECK_NO NUMBER
, GOOD VARCHAR2(300)
, BAD VARCHAR2(300)
, ETC VARCHAR2(300)
,CONSTRAINT CONTENT_CHECK_NO_PK PRIMARY KEY(CHECK_NO)
,CONSTRAINT CONTENT_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST (CHECK_NO)
);

-- 20. 비밀코멘트 (3순위)
CREATE TABLE SECRET_CONTENT
( CHECK_NO NUMBER
, COMMENTS VARCHAR2(300)
,CONSTRAINT SECRET_CONTENT_CHECK_NO_PK PRIMARY KEY(CHECK_NO)
,CONSTRAINT SECRET_CONTENT_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST (CHECK_NO)
);

-- 21. 생활편의시설 (3순위)
CREATE TABLE CONVENIENCE
( CHECK_NO NUMBER
, MART NUMBER(1)
, LAUNDRY NUMBER(1)
, HOSPITAL NUMBER(1)
, FOOD NUMBER(1)
, CULTURE NUMBER(1)
, PARK NUMBER(1)
, COMMENTS VARCHAR2(300)
,CONSTRAINT CONVENIENCE_CHECK_NO_PK PRIMARY KEY(CHECK_NO)
,CONSTRAINT CONVENIENCE_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST (CHECK_NO)
);

-- 22. 추가항목(시간 평가) (3순위)
CREATE TABLE PLUS_TIME
( PTIME_NO NUMBER
, CHECK_NO NUMBER
, TITLE VARCHAR2(20)
, COMMENTS VARCHAR2(300)
, TIME NUMBER(3)
,CONSTRAINT PLUS_TIME_PTIME_NO_PK PRIMARY KEY(PTIME_NO)
,CONSTRAINT PLUS_TIME_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST (CHECK_NO)
);

-- 23. 추가항목(점수 평가) (3순위)
CREATE TABLE PLUS_SCORE
( PSCORE_NO NUMBER
, CHECK_NO NUMBER
, TITLE VARCHAR2(20)
, COMMENTS VARCHAR2(300)
, SCORENO NUMBER
,CONSTRAINT PLUS_SCORE_PSCORE_NO_PK PRIMARY KEY(PSCORE_NO)
,CONSTRAINT PLUS_SCORE_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST (CHECK_NO)
);

-- 24. 교통혼잡도 (3순위)
CREATE TABLE HONJAP
( CHECK_NO NUMBER
, COMMENTS VARCHAR2(300)
, SCORENO NUMBER
,CONSTRAINT HONJAP_CHECK_NO_PK PRIMARY KEY(CHECK_NO)
,CONSTRAINT HONJAP_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST (CHECK_NO)
);

-- 25. 대중교통 (3순위)
CREATE TABLE TRANSPORT
( CHECK_NO NUMBER
, COMMENTS VARCHAR2(300)
, SCORENO NUMBER NOT NULL
,CONSTRAINT TRANSPORT_CHECK_NO_PK PRIMARY KEY(CHECK_NO)
,CONSTRAINT TRANSPORT_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST (CHECK_NO)
);

-- 26. 치안
CREATE TABLE SECURITY
( CHECK_NO      NUMBER          NOT NULL
, COMMENTS       VARCHAR2(300)
, SCORENO       NUMBER          NOT NULL
, CONSTRAINT SECURITY_CHECK_NO_PK PRIMARY KEY(CHECK_NO)
, CONSTRAINT SECURITY_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
             REFERENCES CHECKLIST(CHECK_NO)
, CONSTRAINT SECURITY_SCORENO_FK FOREIGN KEY(SCORENO)
             REFERENCES SCORE(SCORENO)
);

-- 27. 월세
CREATE TABLE WOLSE          -- 월세 (3순위)
( CHECK_NO      NUMBER  NOT NULL
, MWOLSE        NUMBER
, DEPOSIT       NUMBER
, CONSTRAINT WOLSE_CHECKNO_PK PRIMARY KEY(CHECK_NO)
, CONSTRAINT WOLSE_CHECKNO_FK FOREIGN KEY(CHECK_NO)
            REFERENCES CHECKLIST(CHECK_NO)
);

-- 28. 전세
CREATE TABLE JEONSE         -- 전세 (3순위)
( CHECK_NO      NUMBER  NOT NULL
, MJEONSE       NUMBER
, CONSTRAINT JEONSE_CHECKNO_PK PRIMARY KEY(CHECK_NO)
, CONSTRAINT JEONSE_CHECKNO_FK FOREIGN KEY(CHECK_NO)
            REFERENCES CHECKLIST(CHECK_NO)
);

-- 29. 매매
CREATE TABLE MAEMAE         -- 매매 (3순위)
( CHECK_NO      NUMBER  NOT NULL
, MMAEMAE       NUMBER
, CONSTRAINT MAEMAE_CHECKNO_PK PRIMARY KEY(CHECK_NO)
, CONSTRAINT MAEMAE_CHECKNO_FK FOREIGN KEY(CHECK_NO)
            REFERENCES CHECKLIST(CHECK_NO)
);

-- 30. 나의 출근시간
CREATE TABLE GOING          -- 나의 출근시간 (3순위)
( CHECK_NO      NUMBER  NOT NULL
, PLACE         VARCHAR2(30)
, TIME          NUMBER(3)
, CONSTRAINT GOING_CHECKNO_PK PRIMARY KEY(CHECK_NO)
, CONSTRAINT GOING_CHECKNO_FK FOREIGN KEY(CHECK_NO)
            REFERENCES CHECKLIST(CHECK_NO)
);

-- 31. 반려동물
CREATE TABLE PET            -- 반려동물 (3순위)
( CHECK_NO      NUMBER  NOT NULL
, COMMENTS      VARCHAR2(300)
, SCORENO       NUMBER  NOT NULL
, CONSTRAINT PET_CHECKNO_PK PRIMARY KEY(CHECK_NO)
, CONSTRAINT PET_CHECKNO_FK FOREIGN KEY(CHECK_NO)
            REFERENCES CHECKLIST(CHECK_NO)
, CONSTRAINT PET_SCORENO_FK FOREIGN KEY(SCORENO)
            REFERENCES SCORE(SCORENO)
);


--4순위
-- 32. 북마크 스티커
CREATE TABLE CHECKSTICKER
( CSTICKER_NO   NUMBER
, AC_NO         NUMBER          NOT NULL
, CONTENT       VARCHAR2(30)
, CONSTRAINT CHECKSTICKER_NO_PK PRIMARY KEY(CSTICKER_NO)
, CONSTRAINT CHECKSTICKER_AC_NO_FK FOREIGN KEY(AC_NO)
REFERENCES ACCOUNT(AC_NO)
);

-- 33. 북마크 지역정보
CREATE TABLE LOCAL_BOOKMARK
( LO_B_NO   NUMBER
, DONG_NO   NUMBER  NOT NULL
, AC_NO     NUMBER  NOT NULL
, MARKDATE  DATE    NOT NULL
, CONSTRAINT LOCALMARK_LO_B_NO_PK PRIMARY KEY(LO_B_NO)
, CONSTRAINT LOCALMARK_DONG_NO_FK FOREIGN KEY(DONG_NO)
REFERENCES DONG(DONG_NO)
, CONSTRAINT LOCALMARK_AC_NO_FK FOREIGN KEY(AC_NO)
REFERENCES ACCOUNT(AC_NO)
, CONSTRAINT LOCALMARK_DONGAC_UK UNIQUE(DONG_NO, AC_NO)
);

-- 34. 북마크 체크리스트
CREATE TABLE CHECK_BOOKMARK
( CH_B_NO   NUMBER
, CHECK_NO  NUMBER          NOT NULL
, TITLE     VARCHAR2(30)
, AC_NO     NUMBER          NOT NULL
, MARKDATE  DATE            NOT NULL
, CONSTRAINT CBOOKMARK_CH_B_NO_FK PRIMARY KEY(CH_B_NO)
, CONSTRAINT CBOOKMARK_AC_NO_FK FOREIGN KEY(AC_NO)
REFERENCES ACCOUNT(AC_NO)
, CONSTRAINT CBOOKMARK_CHECK_NO_FK FOREIGN KEY(CHECK_NO)
REFERENCES CHECKLIST(CHECK_NO)
, CONSTRAINT CBOOKMARK_CHECKAC_UK UNIQUE(CHECK_NO, AC_NO)
);

--5순위
-- 35. 지역정보 부착 스티커
CREATE TABLE LOCALTAG
( LO_TAG_NO NUMBER
, LO_B_NO   NUMBER  NOT NULL
, STIKER_NO NUMBER  NOT NULL
, CONSTRAINT LOCALTAG_LO_TAG_NO_PK PRIMARY KEY(LO_TAG_NO)
, CONSTRAINT LOCALTAG_LO_B_NO_FK FOREIGN KEY(LO_B_NO)
            REFERENCES LOCAL_BOOKMARK(LO_B_NO)
);

-- 36. 체크리스트 부착 스티커
CREATE TABLE CHECKTAG
( CH_TAG_NO     NUMBER
, CH_B_NO       NUMBER  NOT NULL
, CSTICKER_NO   NUMBER  NOT NULL
, CONSTRAINT CHECKTAG_NO_PK PRIMARY KEY(CH_TAG_NO)
, CONSTRAINT CHECKTAG_CH_B_NO_FK FOREIGN KEY(CH_B_NO)
REFERENCES CHECK_BOOKMARK(CH_B_NO)
, CONSTRAINT CHECKTAG_STICKER_NO_FK FOREIGN KEY(CSTICKER_NO)
REFERENCES CHECKSTICKER(CSTICKER_NO)
);